---
title: ActiveSupport::Rescuable::ClassMethods
layout: default
---
<div class="main">
    <div class="banner">
        
            <span>Ruby on Rails 7.1.5</span><br />
        
        <div class="type">Module</div>
        <h1>
            ActiveSupport::Rescuable::ClassMethods
            
        </h1>
        <ul class="files">
            
            <li><a href="../../../files/activesupport/lib/active_support/rescuable_rb.html">activesupport/lib/active_support/rescuable.rb</a></li>
            
        </ul>
    </div>
    <div id="bodyContent">
        <div id="content">
  

  

  
  


  

  
    <h2 id="methods">Methods</h2>
    <ul>
      
        <li>
          <a href="#method-i-rescue_from">rescue_from</a>
        </li>
      
        <li>
          <a href="#method-i-rescue_with_handler">rescue_with_handler</a>
        </li>
      
    </ul>
  

  

  
    

    

    

    

    <!-- Methods -->
    
    
      <h2 id="instance-public-methods">Instance Public methods</h2>
      
        <div class="method">
          <h3 id="method-i-rescue_from">
            
              rescue_from(*klasses, with: nil, &amp;block)
            
          </h3>

          
            <div class="description">
              <p>Registers exception classes with a handler to be called by <code>rescue_with_handler</code>.</p>

<p><code>rescue_from</code> receives a series of exception classes or class names, and an exception handler specified by a trailing <code>:with</code> option containing the name of a method or a Proc object. Alternatively, a block can be given as the handler.</p>

<p>Handlers that take one argument will be called with the exception, so that the exception can be inspected when dealing with it.</p>

<p>Handlers are inherited. They are searched from right to left, from bottom to top, and up the hierarchy. The handler of the first class for which <code>exception.is_a?(klass)</code> holds true is the one invoked, if any.</p>

<pre><code>class ApplicationController &lt; ActionController::Base
  rescue_from User::NotAuthorized, with: :deny_access
  rescue_from ActiveRecord::RecordInvalid, with: :show_record_errors

  rescue_from &quot;MyApp::BaseError&quot; do |exception|
    redirect_to root_url, alert: exception.message
  end

  private
    def deny_access
      head :forbidden
    end

    def show_record_errors(exception)
      redirect_back_or_to root_url, alert: exception.record.errors.full_messages.to_sentence
    end
end
</code></pre>

<p>Exceptions raised inside exception handlers are not propagated up.</p>
            </div>
          

          

          

          
          
            <details class="method__source">
              <summary>
                <span class="label">üìù Source code</span>
              </summary>

              <pre><code class="ruby"># File activesupport/lib/active_support/rescuable.rb, line 53
      def rescue_from(*klasses, with: nil, &amp;block)
        unless with
          if block_given?
            with = block
          else
            raise ArgumentError, &quot;Need a handler. Pass the with: keyword argument or provide a block.&quot;
          end
        end

        klasses.each do |klass|
          key = if klass.is_a?(Module) &amp;&amp; klass.respond_to?(:===)
            klass.name
          elsif klass.is_a?(String)
            klass
          else
            raise ArgumentError, &quot;#{klass.inspect} must be an Exception class or a String referencing an Exception class&quot;
          end

          # Put the new handler at the end because the list is read in reverse.
          self.rescue_handlers += [[key, with]]
        end
      end</code></pre>
              
                <a href="https://github.com/rails/rails/blob/8984f4c4982f5c94bd6fb8ada42d7418bc403076/activesupport/lib/active_support/rescuable.rb#L53" target="_blank" class="github_url">üîé See on GitHub</a>
              
            </details>
          
        </div>
        
        <div class="method">
          <h3 id="method-i-rescue_with_handler">
            
              rescue_with_handler(exception, object: self, visited_exceptions: [])
            
          </h3>

          
            <div class="description">
              <p>Matches an exception to a handler based on the exception class.</p>

<p>If no handler matches the exception, check for a handler matching the (optional) <code>exception.cause</code>. If no handler matches the exception or its cause, this returns <code>nil</code>, so you can deal with unhandled exceptions. Be sure to re-raise unhandled exceptions if this is what you expect.</p>

<pre><code>begin
  # ...
rescue =&gt; exception
  rescue_with_handler(exception) || raise
end
</code></pre>

<p>Returns the exception if it was handled and <code>nil</code> if it was not.</p>
            </div>
          

          

          

          
          
            <details class="method__source">
              <summary>
                <span class="label">üìù Source code</span>
              </summary>

              <pre><code class="ruby"># File activesupport/lib/active_support/rescuable.rb, line 90
      def rescue_with_handler(exception, object: self, visited_exceptions: [])
        visited_exceptions &lt;&lt; exception

        if handler = handler_for_rescue(exception, object: object)
          handler.call exception
          exception
        elsif exception
          if visited_exceptions.include?(exception.cause)
            nil
          else
            rescue_with_handler(exception.cause, object: object, visited_exceptions: visited_exceptions)
          end
        end
      end</code></pre>
              
                <a href="https://github.com/rails/rails/blob/8984f4c4982f5c94bd6fb8ada42d7418bc403076/activesupport/lib/active_support/rescuable.rb#L90" target="_blank" class="github_url">üîé See on GitHub</a>
              
            </details>
          
        </div>
        
      
    
  
</div>

    </div>
</div>
